"""task audit log

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 14:38:57.951918

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "pending",
                "in_progress",
                "done",
                "cancelled",
                name="from_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "pending",
                "in_progress",
                "done",
                "cancelled",
                name="to_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_status IN ('pending', 'in_progress', 'done', 'cancelled')",
            name=op.f("ck_task_audit_logs_from_status"),
        ),
        sa.CheckConstraint(
            "to_status IN ('pending', 'in_progress', 'done', 'cancelled')",
            name=op.f("ck_task_audit_logs_to_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_audit_logs")),
    )
    op.create_index("ix_task_audit_logs_task_id", "task_audit_logs", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_audit_logs_task_id", table_name="task_audit_logs")
    op.drop_table("task_audit_logs")
    # ### end Alembic commands ###
